version: '3.7'

services:
    swbuild:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                uid: ${uid}
                gid: ${gid}
                username: ${username}
        image: swbuild-ubuntu 
        container_name: swbuild-ubuntu
        restart: on-failure
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - TZ=Europe/London
            - DEBIAN_FRONTEND=noninteractive
        tty: true
